services:
  - type: web
    name: scholi-backend
    env: docker
    branch: main
    dockerfilePath: school_calendar_nest_prisma/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "postgres://user:password@host:5432/dbname" # temporary for demo
      - key: JWT_SECRET
        value: "replace_me"
    repo: https://github.com/mejakivos/scholi-demo

  - type: web
    name: scholi-frontend
    env: static
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: school_calendar_deliverables/frontend/dist
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: "/"
    repo: https://github.com/mejakivos/scholi-demo






