databases:
  - name: scholi-db
    plan: starter
    region: oregon

services:
  - type: web_service
    name: scholi-backend
    env: docker
    branch: main
    dockerfilePath: school_calendar_nest_prisma/Dockerfile
    buildCommand: npm install && npm run build
    startCommand: node dist/main.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scholi-db
          property: connectionString
      - key: JWT_SECRET
        value: "replace_me"
    repo: https://github.com/mejakivos/scholi-demo

  - type: static_site
    name: scholi-frontend
    branch: main
    buildCommand: npm install && npm run build
    publishPath: school_calendar_deliverables/frontend/dist
    envVars:
      - key: REACT_APP_API_URL
        value: "/"
    repo: https://github.com/mejakivos/scholi-demo

